### PR TITLE
Add analytic continual learning methods, including ACIL and DS-AL.

### PR DESCRIPTION
**Pull request by fang-d**
1. ACIL: Analytic Class-Incremental Learning with Absolute Memorization and Privacy Protection. NeurIPS 2022.
2. DS-AL: A Dual-Stream Analytic Learning for Exemplar-Free Class-Incremental Learning. AAAI 2024.

This commit fixes #70. I think that this commit fixes all the problems raised by @Estrella-fugaz.

### CODE REVIEW

**Comment by zhoudw-zdw** [comment]
Thank you for your interest in our work. Please note that with the latest notification on the code review policy, we cannot promise an exact time for the code review.

https://github.com/G-U-N/PyCIL?tab=readme-ov-file#whats-new

**Comment by CLLab-NJU** [comment]
Please review the PR policy and do not modify the readme file.

https://github.com/G-U-N/PyCIL/blob/master/resources/PR_policy.md

**Comment by caoshuai888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fang-d** [comment]
@CLLab-NJU, I have reverted all changes to `ReadMe.md` in this commit to ensure compliance with the latest code review requirements. I would appreciate your feedback before the future changes in code review policy.

**Pull request merged**
